# Generated by Django 5.1.15 on 2026-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidateprofile_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="ats_score",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Calculated ATS suitability score (0-100)",
            ),
        ),
    ]
