# Generated by Django 5.1.15 on 2026-06-19 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_candidateprofile_ats_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="audit_logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="current_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="ocr_confidence",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="ocr_engine",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="original_file",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/original/"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="parsed_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="resume_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="resume_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
