# Generated by Django 6.0.6 on 2026-06-21 11:27

import apps.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0005_candidateprofile_audit_logs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="full_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                validators=[apps.candidates.models.validate_candidate_name],
            ),
        ),
    ]
