# Generated by Django 5.1.15 on 2026-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_alter_candidateprofile_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="ai_experience_rewrite",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="ai_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="ai_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="original_experience_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="original_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="original_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="raw_resume_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
