# Generated by Django 5.1.15 on 2026-06-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_candidateprofile_ai_experience_rewrite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="candidate_photos/"
            ),
        ),
    ]
