# Generated by Django 5.1.15 on 2026-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0008_candidateprofile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="generated_resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/generated/"
            ),
        ),
    ]
