# Generated by Django 5.1.15 on 2026-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_candidateprofile_generated_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="recruiter_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
