# Generated by Django 5.1.15 on 2026-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0010_candidateprofile_recruiter_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="parser_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="preview_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="scan_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="scan_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="secure_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
