# Generated by Django 5.1.15 on 2026-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0012_alter_certification_options_savedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="preferred_job_role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
