# Generated by Django 5.1.15 on 2026-08-19 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0015_candidateprofile_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentCandidateSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_query", models.CharField(blank=True, max_length=255)),
                ("selected_tags", models.JSONField(blank=True, default=list)),
                ("filters_payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_candidate_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recent candidate search",
                "verbose_name_plural": "recent candidate searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedCandidateSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("search_query", models.CharField(blank=True, max_length=255)),
                ("selected_tags", models.JSONField(blank=True, default=list)),
                ("filters_payload", models.JSONField(blank=True, default=dict)),
                ("results_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_candidate_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved candidate search",
                "verbose_name_plural": "saved candidate searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyDesignation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("canonical_name", models.CharField(db_index=True, max_length=150)),
                ("normalized_name", models.CharField(db_index=True, max_length=150)),
                (
                    "department",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "industry",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level / Fresher"),
                            ("JUNIOR", "Junior / Associate"),
                            ("MID", "Mid-Level / Specialist"),
                            ("SENIOR", "Senior / Lead"),
                            ("MANAGER", "Manager / Head"),
                            ("DIRECTOR", "Director / VP"),
                            ("EXECUTIVE", "C-Level / Executive"),
                        ],
                        db_index=True,
                        default="MID",
                        max_length=50,
                    ),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "taxonomy designation",
                "verbose_name_plural": "taxonomy designations",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="RoleRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("SENIORITY_VARIANT", "Seniority Variant"),
                            ("RELATED_ROLE", "Related Role"),
                            ("FUNCTIONAL_EQUIVALENT", "Functional Equivalent"),
                            ("PARENT_ROLE", "Parent Role"),
                            ("CHILD_ROLE", "Child Role"),
                            ("ADJACENT_ROLE", "Adjacent Role"),
                            ("ALIAS", "Alias"),
                        ],
                        db_index=True,
                        default="RELATED_ROLE",
                        max_length=50,
                    ),
                ),
                ("weight", models.FloatField(db_index=True, default=0.85)),
                ("is_bidirectional", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="candidates.taxonomydesignation",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="candidates.taxonomydesignation",
                    ),
                ),
            ],
            options={
                "verbose_name": "role relationship",
                "verbose_name_plural": "role relationships",
            },
        ),
        migrations.CreateModel(
            name="TaxonomySkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("canonical_name", models.CharField(db_index=True, max_length=150)),
                ("normalized_name", models.CharField(db_index=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical Skill"),
                            ("FUNCTIONAL", "Functional / Domain Skill"),
                            ("SOFT", "Soft Skill"),
                            ("TOOL", "Tool / Technology"),
                            ("DOMAIN", "Industry / Domain"),
                            ("CERTIFICATION", "Certification"),
                        ],
                        db_index=True,
                        default="TECHNICAL",
                        max_length=50,
                    ),
                ),
                ("domain", models.CharField(blank=True, db_index=True, max_length=100)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "taxonomy skill",
                "verbose_name_plural": "taxonomy skills",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="RoleSkillRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY_SKILL", "Primary Core Skill"),
                            ("SECONDARY_SKILL", "Secondary Skill"),
                            ("SUPPORTING_SKILL", "Supporting Skill"),
                            ("DOMAIN_SKILL", "Domain Skill"),
                            ("TOOL", "Tool / Technology"),
                        ],
                        db_index=True,
                        default="PRIMARY_SKILL",
                        max_length=50,
                    ),
                ),
                ("weight", models.FloatField(db_index=True, default=0.9)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_relations",
                        to="candidates.taxonomydesignation",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_relations",
                        to="candidates.taxonomyskill",
                    ),
                ),
            ],
            options={
                "verbose_name": "role skill relationship",
                "verbose_name_plural": "role skill relationships",
            },
        ),
        migrations.CreateModel(
            name="CandidateTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("canonical_name", models.CharField(db_index=True, max_length=150)),
                ("normalized_name", models.CharField(db_index=True, max_length=150)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("DESIGNATION", "Designation / Role"),
                            ("PREVIOUS_DESIGNATION", "Previous Designation"),
                            ("SKILL", "Skill"),
                            ("TOOL", "Tool / Technology"),
                            ("DOMAIN", "Domain / Function"),
                            ("INDUSTRY", "Industry"),
                            ("CERTIFICATION", "Certification"),
                            ("EDUCATION", "Education / Degree"),
                            ("INFERRED_KEYWORD", "Inferred Keyword"),
                        ],
                        db_index=True,
                        default="SKILL",
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(db_index=True, default=0.9)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("resume_parser", "Resume Parser"),
                            ("manual", "Manual Entry"),
                            ("recruiter", "Recruiter Tagged"),
                            ("job_application", "Job Application"),
                            ("AI", "AI Inferred"),
                            ("taxonomy", "Taxonomy Mapped"),
                            ("inferred", "Inferred Rule"),
                        ],
                        db_index=True,
                        default="resume_parser",
                        max_length=50,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_tags",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "candidate tag",
                "verbose_name_plural": "candidate tags",
                "indexes": [
                    models.Index(
                        fields=["normalized_name", "tag_type"],
                        name="candidates__normali_fe00fe_idx",
                    ),
                    models.Index(
                        fields=["canonical_name"], name="candidates__canonic_a1d17a_idx"
                    ),
                    models.Index(
                        fields=["confidence", "source"],
                        name="candidates__confide_305a6d_idx",
                    ),
                    models.Index(
                        fields=["profile", "tag_type"],
                        name="candidates__profile_5a0b46_idx",
                    ),
                ],
                "unique_together": {("profile", "normalized_name", "tag_type")},
            },
        ),
        migrations.AddIndex(
            model_name="taxonomydesignation",
            index=models.Index(
                fields=["normalized_name", "is_active"],
                name="candidates__normali_a37b39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomydesignation",
            index=models.Index(
                fields=["canonical_name", "is_active"],
                name="candidates__canonic_efaa14_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomydesignation",
            index=models.Index(
                fields=["department", "industry"], name="candidates__departm_49d7dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomydesignation",
            index=models.Index(
                fields=["seniority"], name="candidates__seniori_89cb03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolerelation",
            index=models.Index(
                fields=["relation_type", "weight"],
                name="candidates__relatio_f4c595_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolerelation",
            unique_together={("source_role", "target_role", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="taxonomyskill",
            index=models.Index(
                fields=["normalized_name", "is_active"],
                name="candidates__normali_369fde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyskill",
            index=models.Index(
                fields=["canonical_name", "is_active"],
                name="candidates__canonic_46a942_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyskill",
            index=models.Index(
                fields=["domain", "category"], name="candidates__domain_7c98ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleskillrelation",
            index=models.Index(
                fields=["relation_type", "weight"],
                name="candidates__relatio_cb56ad_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roleskillrelation",
            unique_together={("role", "skill", "relation_type")},
        ),
    ]
