# Generated by Django 5.1.15 on 2026-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0016_recentcandidatesearch_savedcandidatesearch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="candidate_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PASSIVE", "Passive"),
                    ("OPEN_TO_WORK", "Open to Work"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("SAVED_FOR_LATER", "Saved for Later"),
                    ("HIRED", "Hired"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="career_break_duration_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="defence_branch",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="disability_category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("FREELANCE", "Freelance"),
                    ("INTERNSHIP", "Internship"),
                    ("TEMPORARY", "Temporary"),
                ],
                db_index=True,
                default="FULL_TIME",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("NOT_SPECIFIED", "Not Specified"),
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="NOT_SPECIFIED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="has_career_break",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="has_defence_background",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="industry",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="is_differently_abled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="is_saved_for_later",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="is_shortlisted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="role_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="willing_to_relocate",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="work_permit_countries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="education",
            name="education_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CORRESPONDENCE", "Correspondence / Distance"),
                    ("ONLINE", "Online Learning"),
                    ("ANY", "Any / Other"),
                ],
                db_index=True,
                default="FULL_TIME",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="is_pursuing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="passing_year",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="qualification_level",
            field=models.CharField(
                choices=[
                    ("UG", "Undergraduate (UG / Bachelor's)"),
                    ("PG", "Postgraduate (PG / Master's)"),
                    ("DOCTORATE", "Doctorate / Ph.D"),
                    ("DIPLOMA", "Diploma / Vocational"),
                    ("CERTIFICATE", "Certificate"),
                    ("OTHER", "Other Qualification"),
                ],
                db_index=True,
                default="UG",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="specialization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
