# Generated by Django 5.1.15 on 2026-10-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0018_bulkresumejob_bulkresumeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="duplicateresumelog",
            name="action_taken",
            field=models.CharField(
                choices=[
                    ("SKIPPED", "Skipped"),
                    ("UPDATED", "Updated"),
                    ("MERGED", "Merged"),
                ],
                max_length=50,
            ),
        ),
    ]
