# Generated by Django 5.1.15 on 2026-10-07 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0019_candidateprofile_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                (
                    "company",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("not_found", "Not Found"),
                            ("found", "Found"),
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                        ],
                        db_index=True,
                        default="not_found",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "phone_status",
                    models.CharField(
                        choices=[
                            ("not_found", "Not Found"),
                            ("found", "Found"),
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                        ],
                        db_index=True,
                        default="not_found",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "enrichment person",
                "verbose_name_plural": "enrichment people",
                "ordering": ["full_name"],
            },
        ),
    ]
