# Generated by Django 6.0.6 on 2026-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("COMPANY_ADMIN", "Company Admin"),
                    ("RECRUITER", "Recruiter"),
                    ("CANDIDATE", "Candidate"),
                ],
                db_index=True,
                default="RECRUITER",
                max_length=20,
            ),
        ),
    ]
