# Generated by Django 5.1.15 on 2026-07-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="email",
            field=models.EmailField(db_index=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
    ]
