# Generated by Django 5.1.15 on 2026-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otpverification_email_alter_otpverification_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recruiter_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("ACTIVE", "Active"),
                    ("REJECTED", "Rejected"),
                    ("SUSPENDED", "Suspended"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
