services:
  - type: web
    name: talentvault
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    disk:
      name: media-volume
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.base
