# Generated by Django 5.1.15 on 2026-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="jd_file",
            field=models.FileField(blank=True, null=True, upload_to="jd_files/"),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("FREELANCE", "Freelance"),
                    ("REMOTE", "Remote"),
                ],
                default="FULL_TIME",
                max_length=50,
            ),
        ),
    ]
