# Generated by Django 5.1.15 on 2026-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_jd_file_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("ON_HOLD", "On Hold"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
