# Generated by Django 5.1.15 on 2026-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="experience_level",
        ),
        migrations.AlterField(
            model_name="job",
            name="max_experience",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum experience in years"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum experience in years"
            ),
        ),
    ]
