# Generated by Django 5.1.15 on 2026-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_job_experience_level_alter_job_max_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assets_required",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required assets (e.g. Bike, Laptop)",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
