# Generated by Django 6.0.6 on 2026-06-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "__first__"),
        ("jobs", "0005_job_assets_required_alter_job_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="clients.client",
            ),
        ),
    ]
