# Generated by Django 5.1.15 on 2026-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("FREELANCE", "Freelance"),
                    ("ON_SITE", "On Site"),
                    ("HYBRID", "Hybrid"),
                    ("WORK_FROM_HOME", "Work From Home"),
                ],
                default="FULL_TIME",
                max_length=50,
            ),
        ),
    ]
