# Generated by Django 5.1.15 on 2026-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("ONSITE", "Onsite"),
                    ("HYBRID", "Hybrid"),
                    ("REMOTE", "Remote"),
                ],
                default="ONSITE",
                max_length=50,
            ),
        ),
    ]
