# Generated by Django 5.1.15 on 2026-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_closed_at_job_closed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="screening_questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
