# Generated by Django 5.1.15 on 2026-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_job_screening_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ai_matching_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="education",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="notice_period",
            field=models.PositiveIntegerField(
                default=30, help_text="Maximum notice period in days"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="preferred_skills_text",
            field=models.TextField(
                blank=True, default="", help_text="Comma separated preferred skills"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills_text",
            field=models.TextField(
                blank=True, default="", help_text="Comma separated required skills"
            ),
        ),
    ]
