# Generated by Django 5.1.15 on 2026-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("STATE", "State"),
                            ("DISTRICT", "District"),
                            ("CITY", "City"),
                            ("OTHER", "Other"),
                        ],
                        default="CITY",
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(default="India", max_length=100)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "state", "country")},
            },
        ),
    ]
