# Generated by Django 5.1.15 on 2026-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SUBMITTED", "Submitted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("JOINED", "Joined"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPLIED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="from_stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SUBMITTED", "Submitted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("JOINED", "Joined"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="to_stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SUBMITTED", "Submitted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("JOINED", "Joined"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
