# Generated by Django 6.0.6 on 2026-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_stage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPLIED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="from_stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="to_stage",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEW", "Interview"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
