# Generated by Django 6.0.6 on 2026-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_application_stage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("SYSTEM_SELECTED", "System Selected"),
                    ("SYSTEM_REJECTED", "System Rejected"),
                    ("SYSTEM_SUBMITTED", "System Submitted"),
                    ("AUTOMATION_SKIPPED", "Automation Skipped"),
                    ("SCREENING_FEEDBACK_PENDING", "Screening Feedback Pending"),
                    ("SCREENING_SELECT", "Screening Select"),
                    ("SCREENING_REJECT", "Screening Reject"),
                    ("INTERVIEW_SCHEDULE", "Interview Schedule"),
                    ("INTERVIEW_IN_PROCESS", "Interview In Process"),
                    ("INTERVIEW_SELECT", "Interview Select"),
                    ("INTERVIEW_REJECT", "Interview Reject"),
                    ("DOCUMENTATION_STAGE", "Documentation Stage"),
                    ("NEGOTIATION_STAGE", "Negotiation Stage"),
                    ("OFFER_STAGE", "Offer Stage"),
                    ("ACCEPTED", "Accepted"),
                    (
                        "JOINING_CONFIRMATION_REQUESTED",
                        "Joining Confirmation Requested",
                    ),
                    ("JOINING_CONFIRMATION_RECEIVED", "Joining Confirmation Received"),
                    ("JOINED", "Joined"),
                    ("DROPOUT", "Dropout"),
                    ("CLIENT_DUPLICATE", "Client Duplicate"),
                    ("HOLD", "Hold"),
                    ("RESIGNED", "Resigned"),
                    ("RELIEVED", "Relieved"),
                ],
                db_index=True,
                default="OPEN",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="from_stage",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("SYSTEM_SELECTED", "System Selected"),
                    ("SYSTEM_REJECTED", "System Rejected"),
                    ("SYSTEM_SUBMITTED", "System Submitted"),
                    ("AUTOMATION_SKIPPED", "Automation Skipped"),
                    ("SCREENING_FEEDBACK_PENDING", "Screening Feedback Pending"),
                    ("SCREENING_SELECT", "Screening Select"),
                    ("SCREENING_REJECT", "Screening Reject"),
                    ("INTERVIEW_SCHEDULE", "Interview Schedule"),
                    ("INTERVIEW_IN_PROCESS", "Interview In Process"),
                    ("INTERVIEW_SELECT", "Interview Select"),
                    ("INTERVIEW_REJECT", "Interview Reject"),
                    ("DOCUMENTATION_STAGE", "Documentation Stage"),
                    ("NEGOTIATION_STAGE", "Negotiation Stage"),
                    ("OFFER_STAGE", "Offer Stage"),
                    ("ACCEPTED", "Accepted"),
                    (
                        "JOINING_CONFIRMATION_REQUESTED",
                        "Joining Confirmation Requested",
                    ),
                    ("JOINING_CONFIRMATION_RECEIVED", "Joining Confirmation Received"),
                    ("JOINED", "Joined"),
                    ("DROPOUT", "Dropout"),
                    ("CLIENT_DUPLICATE", "Client Duplicate"),
                    ("HOLD", "Hold"),
                    ("RESIGNED", "Resigned"),
                    ("RELIEVED", "Relieved"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="to_stage",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("SYSTEM_SELECTED", "System Selected"),
                    ("SYSTEM_REJECTED", "System Rejected"),
                    ("SYSTEM_SUBMITTED", "System Submitted"),
                    ("AUTOMATION_SKIPPED", "Automation Skipped"),
                    ("SCREENING_FEEDBACK_PENDING", "Screening Feedback Pending"),
                    ("SCREENING_SELECT", "Screening Select"),
                    ("SCREENING_REJECT", "Screening Reject"),
                    ("INTERVIEW_SCHEDULE", "Interview Schedule"),
                    ("INTERVIEW_IN_PROCESS", "Interview In Process"),
                    ("INTERVIEW_SELECT", "Interview Select"),
                    ("INTERVIEW_REJECT", "Interview Reject"),
                    ("DOCUMENTATION_STAGE", "Documentation Stage"),
                    ("NEGOTIATION_STAGE", "Negotiation Stage"),
                    ("OFFER_STAGE", "Offer Stage"),
                    ("ACCEPTED", "Accepted"),
                    (
                        "JOINING_CONFIRMATION_REQUESTED",
                        "Joining Confirmation Requested",
                    ),
                    ("JOINING_CONFIRMATION_RECEIVED", "Joining Confirmation Received"),
                    ("JOINED", "Joined"),
                    ("DROPOUT", "Dropout"),
                    ("CLIENT_DUPLICATE", "Client Duplicate"),
                    ("HOLD", "Hold"),
                    ("RESIGNED", "Resigned"),
                    ("RELIEVED", "Relieved"),
                ],
                max_length=40,
            ),
        ),
    ]
