# Generated by Django 5.1.15 on 2026-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="in_pipeline",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
