# Generated by Django 5.1.15 on 2026-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_application_in_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="available_joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="current_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="current_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="current_designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="expected_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="is_immediate_joiner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="notice_period",
            field=models.PositiveIntegerField(
                blank=True, help_text="Notice period in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_work_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="relevant_experience",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="screening_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="application",
            name="total_experience",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
    ]
