# Generated by Django 5.1.15 on 2026-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_application_available_joining_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="available_joining_date",
        ),
        migrations.AddField(
            model_name="application",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="note_to_recruiter",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="application_resumes/"
            ),
        ),
    ]
