# Generated by Django 5.1.15 on 2026-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_remove_application_available_joining_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="current_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="key_skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
