# Generated by Django 5.1.15 on 2026-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0008_application_current_location_application_key_skills_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="preferred_location",
        ),
        migrations.AddField(
            model_name="application",
            name="current_location_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="current_location_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="current_location_tier",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_locations_info",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
