# Generated by Django 5.1.15 on 2026-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_remove_application_preferred_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
