# Generated by Django 5.1.15 on 2026-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_application_recruiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="portfolio_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
