# Generated by Django 5.1.15 on 2026-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_application_linkedin_url_application_portfolio_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="screening_answers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
