# Generated by Django 6.0.6 on 2026-06-22 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "spoc_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="SPOC / HR Name"
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("IT_SERVICES", "IT Services"),
                            ("SOFTWARE_PRODUCT", "Software Product"),
                            ("HEALTHCARE", "Healthcare"),
                            ("FINANCE_BANKING", "Finance & Banking"),
                            ("EDTECH", "EdTech"),
                            ("E_COMMERCE", "E-Commerce"),
                            ("MANUFACTURING", "Manufacturing"),
                            ("TELECOM", "Telecom"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("AUTOMOBILE", "Automobile"),
                            ("RETAIL", "Retail"),
                            ("CONSULTING", "Consulting"),
                            ("MEDIA_ENTERTAINMENT", "Media & Entertainment"),
                            ("LOGISTICS", "Logistics"),
                            ("OTHERS", "Others"),
                        ],
                        db_index=True,
                        default="OTHERS",
                        max_length=50,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-50", "1-50"),
                            ("51-200", "51-200"),
                            ("201-500", "201-500"),
                            ("500+", "500+"),
                        ],
                        default="1-50",
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ["company_name"],
            },
        ),
    ]
