from django.urls import path
from .views import (
    DashboardView,
    RoleRedirectView,
    ShortcutRouteView,
    LandingPageView,
    CandidateDashboardView,
    RecruiterDashboardView,
    RecruiterJobsView,
    ParseJobDescriptionView,
    RecruiterCandidatesView,
    AdminDashboardView,
    AdminRecruiterApprovalsView,
    JobsView,
    JobCreateView,
    JobUpdateView,
    JobDeleteView,
    LocationSearchView,
    CandidateSearchView,
    CandidateAutocompleteView,
    CandidateSuggestionsAPIView,
    CandidateSavedSearchesAPIView,
    CandidateRecentSearchesAPIView,
    CandidateDetailView,
    CandidateUpdateView,
    CandidateDeleteView,
    CandidateRejectView,
    AddToPipelineView,
    BulkAddToPipelineView,
    RemoveFromPipelineView,
    JobCandidatesView,
    SaveCandidateNotesView,
    PublicCandidateProfileView,
    PublicJobShareView,
    PublicJobApplyView,
    ATSPipelineView,
    UpdateApplicationStageView,
    UpdateApplicationStageDirectView,
    CompleteTaskView,
    InterviewsView,
    InterviewCalendarEventsView,
    AnalyticsView,
    SettingsView,
    ProfileSettingsUpdateView,
    CandidateMessageAPIView,
    JobActionView,
    ResumeParserView,
    EmailCampaignsView,
    ExportCandidatesView,
    ExportJobsView,
    ExportInterviewsView,
    CandidateJSONEditView,
    CandidateAIAssistView,
    CandidateVersionRollbackView,
    CandidateDuplicateView,
    CandidateExportPDFView,
    CandidateResumePreviewView,
    CandidateResumeDownloadView,
    PublicCandidateResumePreviewView,
    PublicCandidateResumeDownloadView,
    CandidateProfileView,
    CandidateCareerResourcesView,
    CandidateSavedJobsView,
    CandidateRecommendedJobsView,
    CandidateApplicationsView,
    EmployerLandingView,
    CandidateResumeUploadView,
    CandidateResumeDeleteView,
    CandidateOnboardingUpdateView,
    ToggleSaveJobView,
    JobApplyView,
    PublicJobJDPreviewView,
    PublicJobJDDownloadView
)

app_name = 'frontend'

urlpatterns = [
    path('', LandingPageView.as_view(), name='dashboard'),
    path('admin/', ShortcutRouteView.as_view(), {'target': 'admin'}, name='admin_shortcut'),
    path('candidate/', ShortcutRouteView.as_view(), {'target': 'candidate'}, name='candidate_shortcut'),
    path('recruiter/', ShortcutRouteView.as_view(), {'target': 'recruiter'}, name='recruiter_shortcut'),
    path('accounts/login-redirect/', RoleRedirectView.as_view(), name='login_redirect'),
    path('employers/', EmployerLandingView.as_view(), name='employer_landing'),
    path('dashboard/candidate/', CandidateDashboardView.as_view(), name='candidate_dashboard'),
    path('profile/', CandidateProfileView.as_view(), name='candidate_profile'),
    path('profile/resume/upload/', CandidateResumeUploadView.as_view(), name='candidate_resume_upload_ajax'),
    path('profile/resume/delete/', CandidateResumeDeleteView.as_view(), name='candidate_resume_delete_ajax'),
    path('profile/onboarding/update/', CandidateOnboardingUpdateView.as_view(), name='candidate_onboarding_update'),

    path('career-resources/', CandidateCareerResourcesView.as_view(), name='candidate_career_resources'),
    path('jobs/saved/', CandidateSavedJobsView.as_view(), name='candidate_saved_jobs'),
    path('jobs/saved/toggle/', ToggleSaveJobView.as_view(), name='toggle_saved_job'),
    path('jobs/recommended/', CandidateRecommendedJobsView.as_view(), name='candidate_recommended_jobs'),
    path('applications/', CandidateApplicationsView.as_view(), name='candidate_applications'),
    path('dashboard/recruiter/', RecruiterDashboardView.as_view(), name='recruiter_dashboard'),
    path('recruiter/jobs/', RecruiterJobsView.as_view(), name='recruiter_jobs'),
    path('recruiter/jobs/parse-jd/', ParseJobDescriptionView.as_view(), name='parse_jd'),
    path('recruiter/candidates/', RecruiterCandidatesView.as_view(), name='recruiter_candidates'),
    path('dashboard/recruiter/complete-task/', CompleteTaskView.as_view(), name='complete_task'),
    path('dashboard/admin/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('dashboard/admin/recruiter-approvals/', AdminRecruiterApprovalsView.as_view(), name='admin_recruiter_approvals'),
    
    path('jobs/', JobsView.as_view(), name='jobs'),
    path('jobs/new/', JobCreateView.as_view(), name='job_create'),
    path('jobs/<uuid:job_id>/candidates/', JobCandidatesView.as_view(), name='job_candidates'),
    path('jobs/<uuid:pk>/edit/', JobUpdateView.as_view(), name='job_edit'),
    path('jobs/<uuid:pk>/delete/', JobDeleteView.as_view(), name='job_delete'),
    path('jobs/<uuid:pk>/<str:action>/', JobActionView.as_view(), name='job_action'),
    path('jobs/share/<uuid:pk>/', PublicJobShareView.as_view(), name='public_job_share'),
    path('share/job/<uuid:pk>/', PublicJobShareView.as_view(), name='public_job_share_alt'),
    path('jobs/share/<uuid:pk>/jd-preview/', PublicJobJDPreviewView.as_view(), name='share_job_jd_preview'),
    path('jobs/share/<uuid:pk>/jd-download/', PublicJobJDDownloadView.as_view(), name='share_job_jd_download'),
    path('jobs/<uuid:pk>/jd-preview/', PublicJobJDPreviewView.as_view(), name='job_jd_preview'),
    path('jobs/<uuid:pk>/jd-download/', PublicJobJDDownloadView.as_view(), name='job_jd_download'),
    path('jobs/share/<uuid:job_id>/apply/', PublicJobApplyView.as_view(), name='public_job_apply'),
    path('jobs/<uuid:job_id>/apply/', JobApplyView.as_view(), name='job_apply'),
    path('location-search/', LocationSearchView.as_view(), name='location_search'),
    
    path('candidates/', CandidateSearchView.as_view(), name='candidate_search'),
    path('api/candidates/autocomplete/', CandidateAutocompleteView.as_view(), name='candidate_autocomplete'),
    path('api/candidates/suggestions/', CandidateSuggestionsAPIView.as_view(), name='candidate_suggestions'),
    path('api/candidates/saved-searches/', CandidateSavedSearchesAPIView.as_view(), name='candidate_saved_searches'),
    path('api/candidates/saved-searches/<uuid:pk>/', CandidateSavedSearchesAPIView.as_view(), name='candidate_saved_search_detail'),
    path('api/candidates/recent-searches/', CandidateRecentSearchesAPIView.as_view(), name='candidate_recent_searches'),
    path('candidates/<uuid:pk>/', CandidateDetailView.as_view(), name='candidate_detail'),
    path('candidates/<uuid:pk>/edit/', CandidateUpdateView.as_view(), name='candidate_edit'),
    path('candidates/<uuid:id>/delete/', CandidateDeleteView.as_view(), name='candidate_delete'),
    path('candidates/<uuid:pk>/reject/', CandidateRejectView.as_view(), name='candidate_reject'),
    path('candidates/<uuid:pk>/add-to-pipeline/', AddToPipelineView.as_view(), name='add_to_pipeline'),
    path('candidates/bulk-add-to-pipeline/', BulkAddToPipelineView.as_view(), name='bulk_add_to_pipeline'),
    path('remove-from-pipeline/<uuid:pk>/', RemoveFromPipelineView.as_view(), name='remove_from_pipeline'),
    path('candidates/<uuid:pk>/save-notes/', SaveCandidateNotesView.as_view(), name='save_candidate_notes'),
    
    # Resume Intelligence API Endpoints
    path('candidates/<uuid:pk>/edit-json/', CandidateJSONEditView.as_view(), name='candidate_edit_json'),
    path('candidates/<uuid:pk>/ai-improve/', CandidateAIAssistView.as_view(), name='candidate_ai_improve'),
    path('candidates/<uuid:pk>/rollback/', CandidateVersionRollbackView.as_view(), name='candidate_rollback'),
    path('candidates/<uuid:pk>/duplicates/', CandidateDuplicateView.as_view(), name='candidate_duplicates'),
    path('candidates/<uuid:pk>/export/', CandidateExportPDFView.as_view(), name='candidate_export_pdf'),
    
    # Resume Preview & Download
    path('candidates/<uuid:pk>/resume/preview/', CandidateResumePreviewView.as_view(), name='candidate_resume_preview'),
    path('candidates/<uuid:pk>/resume/download/', CandidateResumeDownloadView.as_view(), name='candidate_resume_download'),
    
    path('share/candidate/<uuid:pk>/', PublicCandidateProfileView.as_view(), name='public_candidate_profile'),
    path('share/candidate/<uuid:pk>/resume-preview/', PublicCandidateResumePreviewView.as_view(), name='share_resume_preview'),
    path('share/candidate/<uuid:pk>/resume-download/', PublicCandidateResumeDownloadView.as_view(), name='share_resume_download'),
    path('pipeline/', ATSPipelineView.as_view(), name='ats_pipeline'),
    path('pipeline/update-stage/', UpdateApplicationStageView.as_view(), name='update_application_stage'),
    path('pipeline/update-stage/<uuid:app_id>/', UpdateApplicationStageDirectView.as_view(), name='update_application_stage_direct'),
    path('interviews/', InterviewsView.as_view(), name='interviews'),
    path('interviews/events/', InterviewCalendarEventsView.as_view(), name='interview_calendar_events'),
    path('analytics/', AnalyticsView.as_view(), name='analytics'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('settings/profile/update/', ProfileSettingsUpdateView.as_view(), name='profile_settings_update'),
    path('messages/api/', CandidateMessageAPIView.as_view(), name='candidate_message_api'),
    path('resume-parser/', ResumeParserView.as_view(), name='resume_parser'),
    path('email-campaigns/', EmailCampaignsView.as_view(), name='email_campaigns'),
    
    path('export/candidates/', ExportCandidatesView.as_view(), name='export_candidates'),
    path('export/jobs/', ExportJobsView.as_view(), name='export_jobs'),
    path('export/interviews/', ExportInterviewsView.as_view(), name='export_interviews'),
]
