# Generated by Django 5.1.15 on 2026-06-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="round",
            field=models.CharField(
                blank=True,
                help_text="e.g. Technical Round 1",
                max_length=100,
                null=True,
            ),
        ),
    ]
