# Generated by Django 5.1.15 on 2026-08-19 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "industry",
                "verbose_name_plural": "industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "issuing_organization",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("validity_years", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="taxonomy.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "certification",
                "verbose_name_plural": "certifications",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="JobFunction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_functions",
                        to="taxonomy.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job function",
                "verbose_name_plural": "job functions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry-Level / Fresher"),
                            ("JUNIOR", "Junior / Associate / Officer"),
                            ("MID", "Mid-Level / Specialist / Executive"),
                            ("SENIOR", "Senior / Lead / Principal"),
                            ("MANAGER", "Manager / Assistant Manager / Deputy Manager"),
                            ("DIRECTOR", "Director / Head / VP / AVP"),
                            ("EXECUTIVE", "CXO / President / Executive"),
                        ],
                        db_index=True,
                        default="MID",
                        max_length=30,
                    ),
                ),
                (
                    "typical_experience",
                    models.CharField(
                        choices=[
                            ("FRESHER", "0 - 1 Years"),
                            ("EARLY_CAREER", "1 - 3 Years"),
                            ("MID_CAREER", "3 - 6 Years"),
                            ("SENIOR_CAREER", "6 - 10 Years"),
                            ("LEADERSHIP", "10+ Years"),
                        ],
                        db_index=True,
                        default="MID_CAREER",
                        max_length=30,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Search ranking importance weight (0.1 - 2.0)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_roles",
                        to="taxonomy.department",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_roles",
                        to="taxonomy.industry",
                    ),
                ),
                (
                    "job_function",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_roles",
                        to="taxonomy.jobfunction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job role",
                "verbose_name_plural": "job roles",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="IndustryRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_role_mappings",
                        to="taxonomy.industry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_industry_mappings",
                        to="taxonomy.jobrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "industry role mapping",
                "verbose_name_plural": "industry role mappings",
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("DIPLOMA", "Diploma / Vocational"),
                            ("BACHELORS", "Bachelor's Degree"),
                            ("MASTERS", "Master's Degree / Postgraduate"),
                            ("DOCTORATE", "Doctorate / Ph.D"),
                            ("PROFESSIONAL", "Professional Qualification (CA/CS/CMA)"),
                        ],
                        db_index=True,
                        default="BACHELORS",
                        max_length=30,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "qualification",
                "verbose_name_plural": "qualifications",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depth", models.PositiveIntegerField(default=1)),
                (
                    "ladder_track",
                    models.CharField(
                        blank=True,
                        default="Standard",
                        help_text="e.g. Individual Contributor, Management, Technical",
                        max_length=100,
                    ),
                ),
                (
                    "child_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_hierarchies",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subordinate_hierarchies",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "role hierarchy",
                "verbose_name_plural": "role hierarchies",
            },
        ),
        migrations.CreateModel(
            name="RoleRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            (
                                "PARENT_ROLE",
                                "Parent / Senior Hierarchy Role (e.g. Sales Manager -> ASM)",
                            ),
                            ("CHILD_ROLE", "Child / Subordinate Role"),
                            (
                                "SENIORITY_VARIANT",
                                "Seniority Variant (e.g. Senior Software Engineer -> Software Engineer)",
                            ),
                            (
                                "RELATED_ROLE",
                                "Related Functional Role (e.g. Sales Manager -> BD Manager)",
                            ),
                            (
                                "FUNCTIONAL_EQUIVALENT",
                                "Functional Equivalent (e.g. Sales Executive <-> Sales Officer)",
                            ),
                            (
                                "ADJACENT_ROLE",
                                "Adjacent Lateral Role (e.g. Service Advisor <-> Automobile Technician)",
                            ),
                            ("CROSS_INDUSTRY", "Cross-Industry Transferable Role"),
                        ],
                        db_index=True,
                        default="RELATED_ROLE",
                        max_length=30,
                    ),
                ),
                ("weight", models.FloatField(db_index=True, default=0.85)),
                ("is_bidirectional", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_role_relations",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_role_relations",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "role relationship",
                "verbose_name_plural": "role relationships",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical / Hard Skill"),
                            ("FUNCTIONAL", "Functional / Business Skill"),
                            ("DOMAIN", "Domain / Industry Knowledge"),
                            ("SOFT_SKILL", "Soft / Interpersonal Skill"),
                            ("MANAGERIAL", "Management & Leadership"),
                            ("TOOL", "Tool / Software"),
                            ("LANGUAGE", "Language / Communication"),
                        ],
                        db_index=True,
                        default="TECHNICAL",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "skill category",
                "verbose_name_plural": "skill categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("HARD_SKILL", "Hard / Functional Skill"),
                            ("SOFT_SKILL", "Soft / Cognitive Skill"),
                            ("DOMAIN_KNOWLEDGE", "Domain Knowledge"),
                            ("METHODOLOGY", "Methodology / Framework"),
                        ],
                        db_index=True,
                        default="HARD_SKILL",
                        max_length=30,
                    ),
                ),
                ("is_popular", models.BooleanField(db_index=True, default=False)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="taxonomy.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_function",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specializations",
                        to="taxonomy.jobfunction",
                    ),
                ),
                (
                    "job_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specializations",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "specialization",
                "verbose_name_plural": "specializations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(db_index=True, max_length=100)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("license", models.CharField(default="Open Data", max_length=100)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("duplicates_skipped", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("error_details", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial with Warnings"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("statistics", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "taxonomy import log",
                "verbose_name_plural": "taxonomy import logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "tech_category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_LANGUAGE", "Programming Language"),
                            ("FRAMEWORK", "Framework / Library"),
                            ("DATABASE", "Database / Data Store"),
                            ("CLOUD_PLATFORM", "Cloud Platform / Infrastructure"),
                            ("DEVOPS_TOOL", "DevOps / CI/CD Tool"),
                            ("OPERATING_SYSTEM", "Operating System"),
                            ("AI_FRAMEWORK", "AI / ML / Data Science Stack"),
                        ],
                        db_index=True,
                        default="FRAMEWORK",
                        max_length=40,
                    ),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "technology",
                "verbose_name_plural": "technologies",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        db_index=True,
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="1.0.0", max_length=50),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        default="ODbL / CC BY 4.0 / TV-URT Open",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("CRM", "CRM Platform (Salesforce, HubSpot, Zoho)"),
                            ("ERP", "ERP Platform (SAP, Oracle, Tally)"),
                            ("ANALYTICS", "BI & Analytics (Tableau, PowerBI, Excel)"),
                            ("DESIGN", "Design & CAD (AutoCAD, Figma, SolidWorks)"),
                            (
                                "COLLABORATION",
                                "Productivity & Collaboration (Jira, Slack)",
                            ),
                            (
                                "DIAGNOSTIC",
                                "Industrial / Diagnostic Tool (OBD, Multimeter)",
                            ),
                            ("MEDICAL", "Medical / Lab Equipment"),
                        ],
                        db_index=True,
                        default="ANALYTICS",
                        max_length=30,
                    ),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tool",
                "verbose_name_plural": "tools",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(db_index=True, max_length=200)),
                ("normalized_alias", models.CharField(db_index=True, max_length=200)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("JOB_ROLE", "Job Role / Designation"),
                            ("SKILL", "Skill"),
                            ("TECHNOLOGY", "Technology"),
                            ("TOOL", "Tool"),
                            ("CERTIFICATION", "Certification"),
                            ("QUALIFICATION", "Qualification"),
                        ],
                        db_index=True,
                        default="JOB_ROLE",
                        max_length=30,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            (
                                "ABBREVIATION",
                                "Abbreviation / Short Form (e.g. SDE, BDE)",
                            ),
                            ("SYNONYM", "Synonym / Equivalent Term"),
                            ("ACRONYM", "Acronym (e.g. ASM, BDM, MR)"),
                            (
                                "SPELLING_VARIANT",
                                "Spelling Variant (e.g. React.js, ReactJS)",
                            ),
                            ("SLANG", "Industry Slang / Informal Term"),
                        ],
                        db_index=True,
                        default="SYNONYM",
                        max_length=30,
                    ),
                ),
                ("canonical_name", models.CharField(db_index=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.95)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="taxonomy.skill",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="taxonomy.technology",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="taxonomy.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "taxonomy alias",
                "verbose_name_plural": "taxonomy aliases",
            },
        ),
        migrations.CreateModel(
            name="RoleSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            (
                                "PRIMARY_SKILL",
                                "Primary / Core Skill (High Match Priority)",
                            ),
                            ("SECONDARY_SKILL", "Secondary / Supporting Skill"),
                            ("MANDATORY", "Mandatory Required Skill"),
                            ("DOMAIN_SKILL", "Domain / Functional Competency"),
                            ("TOOL", "Tool / Technology"),
                        ],
                        db_index=True,
                        default="PRIMARY_SKILL",
                        max_length=30,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        db_index=True,
                        default=0.9,
                        help_text="Relationship relevance strength (0.0 to 1.0)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive (Soft-Deleted)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "TV_URT",
                                "TalentVault Universal Recruitment Taxonomy (Core)",
                            ),
                            (
                                "ESCO",
                                "European Skills/Competences and Occupations (ESCO)",
                            ),
                            ("ONET", "O*NET Occupational Information Network"),
                            ("OPEN_DATA", "Open Classification / Public Standards"),
                            ("MANUAL", "Recruiter / Admin Defined"),
                        ],
                        default="TV_URT",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_skills",
                        to="taxonomy.jobrole",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_roles",
                        to="taxonomy.skill",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_roles",
                        to="taxonomy.technology",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_roles",
                        to="taxonomy.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "role skill mapping",
                "verbose_name_plural": "role skill mappings",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_de_normali_668b2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["slug"], name="taxonomy_de_slug_17c534_idx"),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_in_normali_679e0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(fields=["slug"], name="taxonomy_in_slug_69213c_idx"),
        ),
        migrations.AddIndex(
            model_name="jobfunction",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_jo_normali_56693b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobfunction",
            index=models.Index(
                fields=["department", "status"], name="taxonomy_jo_departm_f80da1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_jo_normali_e27a08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["canonical_name", "status"],
                name="taxonomy_jo_canonic_8f6157_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["seniority", "status"], name="taxonomy_jo_seniori_00f59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["industry", "department"], name="taxonomy_jo_industr_86661e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="industryrole",
            unique_together={("industry", "job_role")},
        ),
        migrations.AlterUniqueTogether(
            name="rolehierarchy",
            unique_together={("parent_role", "child_role", "ladder_track")},
        ),
        migrations.AddIndex(
            model_name="rolerelation",
            index=models.Index(
                fields=["relation_type", "weight"],
                name="taxonomy_ro_relatio_12fc2b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolerelation",
            unique_together={("source_role", "target_role", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_sk_normali_94dd7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["canonical_name", "status"],
                name="taxonomy_sk_canonic_2a7019_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category", "status"], name="taxonomy_sk_categor_9f6fef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technology",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_te_normali_e15cdb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technology",
            index=models.Index(
                fields=["canonical_name", "status"],
                name="taxonomy_te_canonic_333cc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technology",
            index=models.Index(
                fields=["tech_category", "status"],
                name="taxonomy_te_tech_ca_58137b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["normalized_name", "status"],
                name="taxonomy_to_normali_3c1c46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["canonical_name", "status"],
                name="taxonomy_to_canonic_c676fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyalias",
            index=models.Index(
                fields=["normalized_alias", "entity_type", "status"],
                name="taxonomy_ta_normali_e65180_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyalias",
            index=models.Index(
                fields=["canonical_name", "status"],
                name="taxonomy_ta_canonic_935c3a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxonomyalias",
            unique_together={("normalized_alias", "entity_type", "canonical_name")},
        ),
        migrations.AddIndex(
            model_name="roleskill",
            index=models.Index(
                fields=["role", "relation_type", "weight"],
                name="taxonomy_ro_role_id_e18f04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roleskill",
            index=models.Index(
                fields=["skill", "weight"], name="taxonomy_ro_skill_i_a4e556_idx"
            ),
        ),
    ]
